"""add season and episode to downloads

Revision ID: 3a33a45e80a0
Revises: f6160b716246
Create Date: 2026-05-04 12:53:28.187338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a33a45e80a0'
down_revision: Union[str, None] = 'f6160b716246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('downloads', sa.Column('season', sa.Integer(), nullable=True))
    op.add_column('downloads', sa.Column('episode', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('downloads', 'episode')
    op.drop_column('downloads', 'season')
    # ### end Alembic commands ###
