"""add user_lists

Revision ID: 528f8ed4833e
Revises: 5963a0323ddc
Create Date: 2026-05-31 23:18:35.566781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '528f8ed4833e'
down_revision: Union[str, None] = '5963a0323ddc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('WATCHED', 'WATCHLIST', name='listkind'), nullable=False),
    sa.Column('media_type', sa.String(length=16), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('poster_path', sa.String(length=255), nullable=True),
    sa.Column('backdrop_path', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("media_type IN ('movie','series','anime')", name='ck_user_lists_media_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tmdb_id', 'media_type', 'kind', name='uq_user_lists_tmdb_type_kind')
    )
    op.create_index(op.f('ix_user_lists_id'), 'user_lists', ['id'], unique=False)
    op.create_index(op.f('ix_user_lists_tmdb_id'), 'user_lists', ['tmdb_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_lists_tmdb_id'), table_name='user_lists')
    op.drop_index(op.f('ix_user_lists_id'), table_name='user_lists')
    op.drop_table('user_lists')
    # ### end Alembic commands ###
