"""add_size_seeds_peers_to_downloads

Revision ID: 5963a0323ddc
Revises: 3a33a45e80a0
Create Date: 2026-05-05 01:51:50.325981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5963a0323ddc'
down_revision: Union[str, None] = '3a33a45e80a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('downloads', sa.Column('size', sa.String(length=50), nullable=True))
    op.add_column('downloads', sa.Column('seeds', sa.Integer(), nullable=True))
    op.add_column('downloads', sa.Column('peers', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('downloads', 'peers')
    op.drop_column('downloads', 'seeds')
    op.drop_column('downloads', 'size')
    # ### end Alembic commands ###
