"""initial migration

Revision ID: f6160b716246
Revises: 
Create Date: 2026-04-30 12:03:55.685750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6160b716246'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('downloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('MOVIE', 'SERIES', 'ANIME', name='contenttype'), nullable=False),
    sa.Column('torrent_name', sa.String(length=500), nullable=True),
    sa.Column('torrent_hash', sa.String(length=64), nullable=True),
    sa.Column('magnet_link', sa.Text(), nullable=True),
    sa.Column('quality', sa.String(length=20), nullable=True),
    sa.Column('language_preference', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'DOWNLOADING', 'COMPLETED', 'FAILED', 'CANCELLED', 'ORGANIZED', name='downloadstatus'), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('speed', sa.String(length=50), nullable=True),
    sa.Column('eta', sa.String(length=50), nullable=True),
    sa.Column('source_folder', sa.Text(), nullable=True),
    sa.Column('destination_folder', sa.Text(), nullable=True),
    sa.Column('indexer_used', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('torrent_hash')
    )
    op.create_index(op.f('ix_downloads_id'), 'downloads', ['id'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    op.drop_index(op.f('ix_downloads_id'), table_name='downloads')
    op.drop_table('downloads')
    # ### end Alembic commands ###
